server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/wired_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spotify.api.client-id=${SPOTIFY_CLIENT_ID}
spotify.api.client-secret=${SPOTIFY_CLIENT_SECRET}

encryption.password=${ENCRYPTION_KEY}
encryption.salt=${ENCRYPTION_SALT}

spotify.redirect.uri=https://127.0.0.1:8080/api/auth/callback
